root: ./

structure:  
    readme: README.md  
    summary: SUMMARY.md
    
redirects:  
    article/5-signup: first_steps/registration.md
    article/12-add-project: first_steps/adding-project/vk-project.md
    article/41-moderation: first_steps/moderation.md
    article/59-transfer-project: first_steps/project-transfer.md
    article/150-list-active-subscriptions: payments/recurring-payments/subscription-list.md
    article/154-create-subscription: payments/recurring-payments/create-subscription.md
    article/151-get-subscription-info: payments/recurring-payments/subscription-info.md
    article/152-close-subscription: payments/recurring-payments/close-subscription.md
    article/31-creating-payment-from-payment-form: payments/create-payment-easy.md
    article/32-creating-payment-via-api: payments/create-payment.md
    article/35-confirmation-payment: payments/payment-handler.md
    article/58-get-payment: payments/payment-info.md
    article/60-refund-payment: payments/payment-refund.md
    article/62-masspayment: payouts/create-payout.md
    article/79-masspayment-status: payouts/payout-info.md
    article/90-bin-check: payouts/card-info-bin.md
    article/63-get-partner: unitpay-management/balance.md
    article/149-project-commissions: unitpay-management/commissions.md
    article/67-ip-addresses: book-of-reference/ip-addresses.md
    article/49-appearance-forms-payment: book-of-reference/payment-form.md
    article/37-operator-codes: book-of-reference/operator-codes.md
    article/36-codes-payment-systems: book-of-reference/payment-system-codes.md
    article/78-qiwi-country-codes: book-of-reference/qiwi-country-codes.md
    article/168-telegram: other/telegram.md
    article/252-article: online-cash-register/receipt_parameters.md
    category/51-category: payments/create-payment-easy.md
    category/87-api: unitpay-management/balance.md
    category/43-category: gotovye-moduli/unitpay-sdk.md
    collection/1-unitpay: payments/create-payment-easy.md

