root: 

structure:  
    readme: README.md  
    summary: SUMMARY.md
    
redirects:  
    article/5-signup: ./first_steps/adding-project
    article/59-transfer-project: ./first_steps/project-transfer.md
